version: "3.8"

services:
  web:
    image: "${DOCKERHUB_USERNAME}/talentora-webapp-staging:latest"
    ports:
      - "443:3000"             # map container’s 3000 → host’s 443
    environment:
      - NODE_ENV=production     # override or add any runtime vars here
      - PORT=3000
    restart: unless-stopped     # keep it up unless you explicitly stop it
    networks:
      - supabase_default

networks:
  supabase_default:
    external: true