services:
  webapp:
    env_file: .env.local
    image: "${DOCKERHUB_USERNAME}/talentora-webapp-staging:latest"
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped