_format_version: "1.1"

consumers:
  - username: anon
    keyauth_credentials:
      - key: SUPABASE_ANON_KEY
  - username: service_role
    keyauth_credentials:
      - key: SUPABASE_SERVICE_ROLE_KEY

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        - X-Requested-With
        - Range
        - apikey
        - prefer
        - x-client-info
      exposed_headers:
        - X-Request-Id
      credentials: true
      preflight_continue: false

services:
  - name: auth-v1-open
    url: http://supabase-auth:9999/
    plugins:
      - name: cors
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - /auth/v1/verify
      - name: auth-v1-open-callback
        strip_path: true
        paths:
          - /auth/v1/callback
      - name: auth-v1-open-authorize
        strip_path: true
        paths:
          - /auth/v1/authorize

  - name: auth-v1
    url: http://supabase-auth:9999/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - /auth/v1/

  - name: rest-v1
    url: http://supabase-rest:3000/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
    routes:
      - name: rest-v1-all
        strip_path: true
        paths:
          - /rest/v1/

  - name: realtime-v1
    url: http://supabase-realtime:4000/socket/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
    routes:
      - name: realtime-v1-all
        strip_path: true
        paths:
          - /realtime/v1/

  - name: storage-v1
    url: http://supabase-storage:5000/
    plugins:
      - name: cors
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - /storage/v1/

  - name: meta
    url: http://supabase-meta:8080/
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
    routes:
      - name: meta-all
        strip_path: true
        paths:
          - /pg/ 