

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "wrappers" WITH SCHEMA "extensions";






CREATE TYPE "public"."pricing_plan_interval" AS ENUM (
    'day',
    'week',
    'month',
    'year'
);


ALTER TYPE "public"."pricing_plan_interval" OWNER TO "postgres";


CREATE TYPE "public"."pricing_type" AS ENUM (
    'one_time',
    'recurring'
);


ALTER TYPE "public"."pricing_type" OWNER TO "postgres";


CREATE TYPE "public"."subscription_status" AS ENUM (
    'trialing',
    'active',
    'canceled',
    'incomplete',
    'incomplete_expired',
    'past_due',
    'unpaid',
    'paused'
);


ALTER TYPE "public"."subscription_status" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_job_interview_config"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$BEGIN
    -- First create the job_interview_config record
    INSERT INTO public.job_interview_config (
        job_id,
        created_at,
        company_context,
        bot_id,
        duration,
        interview_name,
        type,
        hiring_manager_notes
    ) VALUES (
        NEW.merge_id,
        NOW(),
        NEW.company_id,
        null,
        null,
        null,
        null,
        null
    );

    RETURN NEW;
END;$$;


ALTER FUNCTION "public"."handle_new_job_interview_config"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    IF NEW.raw_user_meta_data->>'role' IS NULL THEN
        RAISE EXCEPTION 'No role found in raw_user_meta_data for user: %', NEW.id;
    END IF;

    IF NEW.raw_user_meta_data->>'role' = 'recruiter' THEN
        RAISE NOTICE 'Creating recruiter for user: %', NEW.id;
        INSERT INTO public.recruiters (id) VALUES (NEW.id);
    ELSIF NEW.raw_user_meta_data->>'role' = 'applicant' THEN
        RAISE NOTICE 'Creating applicant for user: %', NEW.id;
        INSERT INTO public.applicants (id) VALUES (NEW.id);
    ELSE
        RAISE EXCEPTION 'Invalid role: %, for user: %', NEW.raw_user_meta_data->>'role', NEW.id;
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."AI_summary" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "emotion_eval" "jsonb",
    "interview_summary" "jsonb",
    "text_eval" "jsonb"
);


ALTER TABLE "public"."AI_summary" OWNER TO "postgres";


COMMENT ON TABLE "public"."AI_summary" IS 'Summarized information per applicant interview';



CREATE TABLE IF NOT EXISTS "public"."applicants" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "merge_applicant_id" "uuid"
);


ALTER TABLE "public"."applicants" OWNER TO "postgres";


COMMENT ON TABLE "public"."applicants" IS 'Applicants';



COMMENT ON COLUMN "public"."applicants"."id" IS 'id';



CREATE TABLE IF NOT EXISTS "public"."applications" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "AI_summary" "uuid",
    "applicant_id" "uuid" NOT NULL,
    "job_id" "uuid" NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."applications" OWNER TO "postgres";


COMMENT ON COLUMN "public"."applications"."AI_summary" IS 'AI summary for interview conducted by each applicants';



COMMENT ON COLUMN "public"."applications"."applicant_id" IS 'applicant unique id';



COMMENT ON COLUMN "public"."applications"."job_id" IS 'unique id for jobs';



CREATE TABLE IF NOT EXISTS "public"."bots" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "voice_id" "text",
    "description" "text",
    "prompt" "text",
    "company_id" "uuid",
    "icon" "text",
    "role" "text"
);


ALTER TABLE "public"."bots" OWNER TO "postgres";


ALTER TABLE "public"."bots" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bots_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."companies" (
    "name" "text" NOT NULL,
    "location" "text",
    "industry" "text",
    "description" "text",
    "email_extension" "text",
    "website_url" "text",
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "subscription_id" "text",
    "billing_address" "text",
    "merge_account_token" "text",
    "payment_method" "text",
    "company_context" "uuid"
);


ALTER TABLE "public"."companies" OWNER TO "postgres";


COMMENT ON COLUMN "public"."companies"."email_extension" IS 'Email extension for these companies (i.e., @bu.edu, @redhat.com, etc)';



COMMENT ON COLUMN "public"."companies"."website_url" IS 'Website URL for the company';



COMMENT ON COLUMN "public"."companies"."id" IS 'Company id';



COMMENT ON COLUMN "public"."companies"."subscription_id" IS 'ID of the subscription';



CREATE TABLE IF NOT EXISTS "public"."company_context" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text",
    "culture" "text",
    "goals" "text",
    "history" "text",
    "products" "text",
    "customers" "text"
);


ALTER TABLE "public"."company_context" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" "uuid" NOT NULL,
    "stripe_customer_id" "text"
);


ALTER TABLE "public"."customers" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."job_interview_config" (
    "job_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "interview_questions" "jsonb",
    "company_context" "uuid",
    "bot_id" bigint,
    "duration" smallint,
    "type" "text",
    "interview_name" "text",
    "hiring_manager_notes" "text",
    "preferred_qual" "jsonb"[],
    "min_qual" "jsonb"[]
);


ALTER TABLE "public"."job_interview_config" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."jobs" (
    "company_id" "uuid",
    "merge_id" "uuid" NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."jobs" OWNER TO "postgres";


COMMENT ON COLUMN "public"."jobs"."company_id" IS 'company id';



CREATE TABLE IF NOT EXISTS "public"."prices" (
    "id" "text" NOT NULL,
    "product_id" "text",
    "active" boolean,
    "description" "text",
    "unit_amount" bigint,
    "currency" "text",
    "type" "public"."pricing_type",
    "interval" "public"."pricing_plan_interval",
    "interval_count" integer,
    "trial_period_days" integer,
    "metadata" "jsonb",
    CONSTRAINT "prices_currency_check" CHECK (("char_length"("currency") = 3))
);


ALTER TABLE "public"."prices" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" "text" NOT NULL,
    "active" boolean,
    "name" "text",
    "description" "text",
    "image" "text",
    "metadata" "jsonb"
);


ALTER TABLE "public"."products" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."recruiters" (
    "id" "uuid" NOT NULL,
    "avatar_url" "text",
    "billing_address" "jsonb",
    "payment_method" "jsonb",
    "company_id" "uuid",
    "harvest_recruiters" integer
);


ALTER TABLE "public"."recruiters" OWNER TO "postgres";


COMMENT ON COLUMN "public"."recruiters"."company_id" IS 'ID for company';



COMMENT ON COLUMN "public"."recruiters"."harvest_recruiters" IS 'id for harvest recruiters object';



CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "id" "text" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "status" "public"."subscription_status",
    "metadata" "jsonb",
    "price_id" "text",
    "quantity" integer,
    "cancel_at_period_end" boolean,
    "created" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "current_period_start" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "current_period_end" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "ended_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "cancel_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "canceled_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "trial_start" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "trial_end" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."subscriptions" OWNER TO "postgres";


ALTER TABLE ONLY "public"."AI_summary"
    ADD CONSTRAINT "AI_summary_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applicants"
    ADD CONSTRAINT "applicants_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "applications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bots"
    ADD CONSTRAINT "bots_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_subscription_id_key" UNIQUE ("subscription_id");



ALTER TABLE ONLY "public"."company_context"
    ADD CONSTRAINT "company_context_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."job_interview_config"
    ADD CONSTRAINT "job_interview_config_pkey" PRIMARY KEY ("job_id");



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_merge_id_key" UNIQUE ("merge_id");



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."prices"
    ADD CONSTRAINT "prices_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recruiters"
    ADD CONSTRAINT "recruiters_harvest_recruiters_key" UNIQUE ("harvest_recruiters");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recruiters"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "on_job_created" AFTER INSERT ON "public"."jobs" FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_job_interview_config"();



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "applications_AI_summary_fkey" FOREIGN KEY ("AI_summary") REFERENCES "public"."AI_summary"("id");



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "applications_applicant_id_fkey" FOREIGN KEY ("applicant_id") REFERENCES "public"."applicants"("id");



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "applications_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("merge_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bots"
    ADD CONSTRAINT "bots_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_company_context_fkey" FOREIGN KEY ("company_context") REFERENCES "public"."company_context"("id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id");



ALTER TABLE ONLY "public"."company_context"
    ADD CONSTRAINT "company_context_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."companies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."job_interview_config"
    ADD CONSTRAINT "job_interview_config_bot_id_fkey" FOREIGN KEY ("bot_id") REFERENCES "public"."bots"("id");



ALTER TABLE ONLY "public"."job_interview_config"
    ADD CONSTRAINT "job_interview_config_company_context_fkey" FOREIGN KEY ("company_context") REFERENCES "public"."company_context"("id");



ALTER TABLE ONLY "public"."job_interview_config"
    ADD CONSTRAINT "job_interview_config_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("merge_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_interview_config"
    ADD CONSTRAINT "job_interview_config_job_id_fkey1" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("merge_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prices"
    ADD CONSTRAINT "prices_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_price_id_fkey" FOREIGN KEY ("price_id") REFERENCES "public"."prices"("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."recruiters"
    ADD CONSTRAINT "users_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow public read-only access." ON "public"."prices" FOR SELECT USING (true);



CREATE POLICY "Allow public read-only access." ON "public"."products" FOR SELECT USING (true);



CREATE POLICY "Allow recruiters to modify company_context" ON "public"."company_context" USING (true);



CREATE POLICY "Can only view own subs data." ON "public"."subscriptions" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Can update own user data." ON "public"."recruiters" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Can view own user data." ON "public"."recruiters" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "Edit job config" ON "public"."job_interview_config" TO "authenticated" USING (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."jobs" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Modify bots" ON "public"."bots" TO "authenticated" USING (true);



CREATE POLICY "Select Jobs" ON "public"."jobs" FOR SELECT USING (true);



CREATE POLICY "View application" ON "public"."applications" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "allow_supabase_service_role" ON "public"."applicants" TO "authenticated", "anon", "supabase_auth_admin" USING (true);



CREATE POLICY "allow_supabase_service_role" ON "public"."recruiters" TO "authenticated", "anon", "supabase_auth_admin" USING (true);



ALTER TABLE "public"."applicants" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."applications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bots" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."companies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."company_context" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_interview_config" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "policy_name" ON "public"."companies" TO "authenticated" USING (true);



ALTER TABLE "public"."prices" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recruiters" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."prices";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."products";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





















































































































































































































































































































GRANT ALL ON FUNCTION "public"."handle_new_job_interview_config"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_job_interview_config"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_job_interview_config"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";
























GRANT ALL ON TABLE "public"."AI_summary" TO "anon";
GRANT ALL ON TABLE "public"."AI_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."AI_summary" TO "service_role";



GRANT ALL ON TABLE "public"."applicants" TO "anon";
GRANT ALL ON TABLE "public"."applicants" TO "authenticated";
GRANT ALL ON TABLE "public"."applicants" TO "service_role";
GRANT INSERT ON TABLE "public"."applicants" TO "supabase_auth_admin";



GRANT ALL ON TABLE "public"."applications" TO "anon";
GRANT ALL ON TABLE "public"."applications" TO "authenticated";
GRANT ALL ON TABLE "public"."applications" TO "service_role";



GRANT ALL ON TABLE "public"."bots" TO "anon";
GRANT ALL ON TABLE "public"."bots" TO "authenticated";
GRANT ALL ON TABLE "public"."bots" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bots_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bots_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bots_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."companies" TO "anon";
GRANT ALL ON TABLE "public"."companies" TO "authenticated";
GRANT ALL ON TABLE "public"."companies" TO "service_role";



GRANT ALL ON TABLE "public"."company_context" TO "anon";
GRANT ALL ON TABLE "public"."company_context" TO "authenticated";
GRANT ALL ON TABLE "public"."company_context" TO "service_role";



GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON TABLE "public"."job_interview_config" TO "anon";
GRANT ALL ON TABLE "public"."job_interview_config" TO "authenticated";
GRANT ALL ON TABLE "public"."job_interview_config" TO "service_role";



GRANT ALL ON TABLE "public"."jobs" TO "anon";
GRANT ALL ON TABLE "public"."jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs" TO "service_role";



GRANT ALL ON TABLE "public"."prices" TO "anon";
GRANT ALL ON TABLE "public"."prices" TO "authenticated";
GRANT ALL ON TABLE "public"."prices" TO "service_role";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";



GRANT ALL ON TABLE "public"."recruiters" TO "anon";
GRANT ALL ON TABLE "public"."recruiters" TO "authenticated";
GRANT ALL ON TABLE "public"."recruiters" TO "service_role";
GRANT INSERT ON TABLE "public"."recruiters" TO "supabase_auth_admin";



GRANT ALL ON TABLE "public"."subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
