name: 'build-test_Next.js'

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  # SUPABASE
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

  SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
  SUPABASE_AUTH_EXTERNAL_GITHUB_REDIRECT_URI: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GITHUB_REDIRECT_URI }}
  SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID }}
  SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET }}

  # STRIPE
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_MANUAL_ROOM_ENTRY: ${{ secrets.NEXT_PUBLIC_MANUAL_ROOM_ENTRY }}
  NEXT_PUBLIC_GROQ_API_KEY: ${{ secrets.NEXT_PUBLIC_GROQ_API_KEY }}


jobs:
  install-and-test: # Validation, lint test.
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install       

      - name: Run Lint
        run: |
          npm run lint
          npm run prettier-fix
        continue-on-error: true
        
      - name: Run Tests
        run: npm test
        continue-on-error: true
        
      - name: Build Next.js project
        run: npm run build

  generate_supabase_types: 
      runs-on: ubuntu-latest
      steps:
          - uses: supabase/setup-cli@v1
            with:
              version: latest
          - run: supabase init
          - run: supabase db start
          - name: Install dependencies
            run: npm install 
          - name: Verify generated types match Postgres schema
            run: |
              ls
              pwd
              npm run supabase:generate-types
              if ! git diff --ignore-space-at-eol --exit-code --quiet types/types_db.ts; then
                echo "Detected uncommitted changes after build. See status below:"
                git diff
                exit 1
              fi


  deploy-preview: # Make sure this can be deployed. Only run when on a pull request
    runs-on: ubuntu-latest
    needs: install-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build for preview
        run: npm run build

      - name: Start Next.js server for preview
        run: npm run start
