name: 'build-test_Next.js'

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  # SUPABASE
  NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ vars.SUPABASE_SERVICE_ROLE_KEY }}
  NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}

  SUPABASE_PASSWORD: ${{ vars.SUPABASE_PASSWORD }}
  SUPABASE_AUTH_EXTERNAL_GITHUB_REDIRECT_URI: ${{ vars.SUPABASE_AUTH_EXTERNAL_GITHUB_REDIRECT_URI }}
  SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID: ${{ vars.SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID }}
  SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET: ${{ vars.SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET }}

  # STRIPE
  STRIPE_SECRET_KEY: ${{ vars.STRIPE_SECRET_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ vars.STRIPE_WEBHOOK_SECRET }}

  NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_MANUAL_ROOM_ENTRY: ${{ vars.NEXT_PUBLIC_MANUAL_ROOM_ENTRY }}
  NEXT_PUBLIC_GROQ_API_KEY: ${{ vars.NEXT_PUBLIC_GROQ_API_KEY }}


jobs:
  install-and-test: # Validation, lint test.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install       

      - name: Run Lint
        run: |
          npm run lint
          npm run prettier-fix
        continue-on-error: true
        
      - name: Run Tests
        run: npm test
        continue-on-error: true
        
      - name: Build Next.js project
        run: npm run build

  generate_types: 
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - uses: supabase/setup-cli@v1
            with:
              version: latest
          - name: init supabase
            run: | 
              supabase init --force
              supabase db start
          - name: Verify generated types match Postgres schema
            run: |
              mkdir -p types
              npx supabase gen types typescript --local --schema public > types/types_db.ts
              if ! git diff --ignore-space-at-eol --exit-code --quiet types/types_db.ts; then
                echo "Detected uncommitted changes after build. See status below:"
                git diff
              else
                echo "No changes detected."
                exit 1
              fi
              
          - name: Set Git config with custom user
            run: |
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add schema.gen.ts
              git commit -m "Update generated types based on Postgres schema"
              git push


  deploy-preview: # Make sure this can be deployed. Only run when on a pull request
    runs-on: ubuntu-latest
    needs: install-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build for preview
        run: npm run build

      - name: Start Next.js server for preview
        run: npm run start
